// <auto-generated />
using System;
using ContactsManager.Console.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsManager.Console.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    partial class ContactsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ContactsManager.Console.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastContactedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Tech Corp",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@example.com",
                            FirstName = "John",
                            LastContactedAt = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            Notes = "CEO of Tech Corp",
                            Phone = "(555) 123-4567"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Design Studio",
                            CreatedAt = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.j@email.com",
                            FirstName = "Sarah",
                            LastContactedAt = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            Notes = "Freelance designer",
                            Phone = "(555) 234-5678"
                        },
                        new
                        {
                            Id = 3,
                            Company = "Global Industries",
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mbrown@company.com",
                            FirstName = "Michael",
                            LastContactedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            Notes = "Project manager",
                            Phone = "(555) 345-6789"
                        },
                        new
                        {
                            Id = 4,
                            Company = "Marketing Plus",
                            CreatedAt = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.davis@mail.com",
                            FirstName = "Emily",
                            LastContactedAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Davis",
                            Notes = "Marketing specialist",
                            Phone = "(555) 456-7890"
                        },
                        new
                        {
                            Id = 5,
                            Company = "Wilson & Associates",
                            CreatedAt = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.w@example.org",
                            FirstName = "David",
                            LastName = "Wilson",
                            Notes = "Legal consultant",
                            Phone = "(555) 567-8901"
                        },
                        new
                        {
                            Id = 6,
                            Company = "Health First",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jen.martinez@email.com",
                            FirstName = "Jennifer",
                            LastContactedAt = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martinez",
                            Notes = "Healthcare provider",
                            Phone = "(555) 678-9012"
                        },
                        new
                        {
                            Id = 7,
                            Company = "Tech Solutions",
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rtaylor@tech.com",
                            FirstName = "Robert",
                            LastContactedAt = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            Notes = "Software engineer",
                            Phone = "(555) 789-0123"
                        },
                        new
                        {
                            Id = 8,
                            Company = "Creative Agency",
                            CreatedAt = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lisa.a@example.com",
                            FirstName = "Lisa",
                            LastContactedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anderson",
                            Notes = "Creative director",
                            Phone = "(555) 890-1234"
                        },
                        new
                        {
                            Id = 9,
                            Company = "Business Ventures",
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "wthomas@business.com",
                            FirstName = "William",
                            LastContactedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            Notes = "Entrepreneur",
                            Phone = "(555) 901-2345"
                        },
                        new
                        {
                            Id = 10,
                            Company = "Education Group",
                            CreatedAt = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amanda.garcia@mail.com",
                            FirstName = "Amanda",
                            LastContactedAt = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Garcia",
                            Notes = "Education coordinator",
                            Phone = "(555) 012-3456"
                        });
                });

            modelBuilder.Entity("ContactsManager.Console.Models.ContactTag", b =>
                {
                    b.Property<int>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContactId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ContactTags");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            TagId = 2
                        },
                        new
                        {
                            ContactId = 1,
                            TagId = 4
                        },
                        new
                        {
                            ContactId = 2,
                            TagId = 2
                        },
                        new
                        {
                            ContactId = 3,
                            TagId = 2
                        },
                        new
                        {
                            ContactId = 4,
                            TagId = 2
                        },
                        new
                        {
                            ContactId = 5,
                            TagId = 2
                        },
                        new
                        {
                            ContactId = 6,
                            TagId = 1
                        },
                        new
                        {
                            ContactId = 7,
                            TagId = 3
                        },
                        new
                        {
                            ContactId = 8,
                            TagId = 2
                        },
                        new
                        {
                            ContactId = 8,
                            TagId = 4
                        },
                        new
                        {
                            ContactId = 9,
                            TagId = 2
                        },
                        new
                        {
                            ContactId = 10,
                            TagId = 5
                        });
                });

            modelBuilder.Entity("ContactsManager.Console.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Friends"
                        },
                        new
                        {
                            Id = 4,
                            Name = "VIP"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Newsletter"
                        });
                });

            modelBuilder.Entity("ContactsManager.Console.Models.ContactTag", b =>
                {
                    b.HasOne("ContactsManager.Console.Models.Contact", "Contact")
                        .WithMany("ContactTags")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactsManager.Console.Models.Tag", "Tag")
                        .WithMany("ContactTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ContactsManager.Console.Models.Contact", b =>
                {
                    b.Navigation("ContactTags");
                });

            modelBuilder.Entity("ContactsManager.Console.Models.Tag", b =>
                {
                    b.Navigation("ContactTags");
                });
#pragma warning restore 612, 618
        }
    }
}
